name = "gateway-demo"
type = "javascript"
workers_dev = true
# Add your account ID here
account_id = ""

[build]
command = "npm run build"
watch_dir = "worker"

[build.upload]
format = "modules"
main = "./index.js"
dir = "build"

[[build.upload.rules]]
globs = ["build/*.js"]
type = "ESModule"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" },
  { name = "LOBBY", class_name = "Lobby" }
]
