name = "gateway-demo"
type = "javascript"
workers_dev = true
# Add your account ID here
account_id = ""

[build]
command = "npm run build:example"
watch_dir = "./example"

[build.upload]
dir = "build"
format = "modules"
main = "./index.js"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" },
  { name = "LOBBY", class_name = "Lobby" }
]
