name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v16
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: (env) pnpm
      run: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm

    - name: (env) cache
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-node14-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-node14-

    - name: Install
      run: pnpm install

    - name: Type Check
      run: pnpm run types

    - name: Compile
      run: pnpm run build

    - name: (example) Type Check
      run: yarn --cwd example types

    - name: (example) Compile
      run: yarn --cwd example build
